name: .NET Framework

on: [ push, pull_request ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet executables
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet packages
      run: nuget restore CmTetris.sln
      
    - name: Build
      run: msbuild CmTetris.sln /p:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-artifacts
        path: |
          SimpleTetris/bin/
          Tetriminify/bin/
          Periotris/bin/
